name: "PR build"

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["darwin", "linux", "freebsd"]
        arch: ["386", "amd64"]
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v2
      - name: "Setup Go environment"
        uses: actions/setup-go@v1
        with:
          go-version: "1.13"
      - name: "Run build & tests"
        env:
          BUILDOS: ${{ matrix.os }}
          BUILDARCH: ${{ matrix.arch }}
          BUILDNAME: parser-${{ matrix.os }}-${{ matrix.arch }}
        run: |
          make test && \
          make verify && \
          make build -e
