name: "Release build"

on:
  push:
    tags:
      # Push events to matching v*, i.e. v1.0, v20.15.10
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["darwin", "linux", "freebsd"]
        arch: ["386", "amd64"]
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v2
      - name: "Setup Go environment"
        uses: actions/setup-go@v1
        with:
          go-version: "1.13"
      - name: "Create build artifact"
        env:
          BUILDOS: ${{ matrix.os }}
          BUILDARCH: ${{ matrix.arch }}
          BUILDNAME: speechly-nluexampleparser-${{ matrix.os }}-${{ matrix.arch }}
        run: |
          make test && \
          make verify && \
          make build -e && \
          tar -czvf ${BUILDNAME}.tar.gz ${BUILDNAME}
      - name: "Upload build artifact"
        uses: actions/upload-artifact@v1
        with:
          name: speechly-nluexampleparser-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
          path: speechly-nluexampleparser-${{ matrix.os }}-${{ matrix.arch }}.tar.gz

  create_release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Create release"
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: "Create release URL file"
        env:
          RELEASE_UPLOAD_URL: ${{ steps.create_release.outputs.upload_url }}
        run: echo ${RELEASE_UPLOAD_URL} > RELEASE_UPLOAD_URL_FILE.txt
      - name: "Upload release URL file"
        uses: actions/upload-artifact@v1
        with:
          name: RELEASE_UPLOAD_URL_FILE
          path: RELEASE_UPLOAD_URL_FILE.txt

  upload_assets:
    runs-on: ubuntu-latest
    needs: create_release
    strategy:
      matrix:
        os: ["darwin", "linux", "freebsd"]
        arch: ["386", "amd64"]
    steps:
      - name: "Download release URL file"
        uses: actions/download-artifact@v1
        with:
          name: RELEASE_UPLOAD_URL_FILE
      - name: "Export release URL"
        id: get_release_url
        run: echo ::set-output name=RELEASE_UPLOAD_URL::$(cat RELEASE_UPLOAD_URL_FILE/RELEASE_UPLOAD_URL_FILE.txt)
      - name: "Download build artifact"
        uses: actions/download-artifact@v1
        with:
          name: speechly-nluexampleparser-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
      - name: "Add build artifact to release"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object,
          # which include a `upload_url`.
          #
          # See this blog post for more info:
          # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          upload_url: ${{ steps.get_release_url.outputs.RELEASE_UPLOAD_URL }}
          asset_path: "speechly-nluexampleparser-${{ matrix.os }}-${{ matrix.arch }}.tar.gz/speechly-nluexampleparser-${{ matrix.os }}-${{ matrix.arch }}.tar.gz"
          asset_name: speechly-nluexampleparser-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
          asset_content_type: application/gzip
